<div class="row login-requests-list-item">
            <div class="col-lg-12 col-md-12 col-xs-12 colsm-12 login-requests-list-item-header">
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6">
                    <span class="lead">Job role</span>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-btn-group">
                    <button class="btn btn-danger pull-right">Delete request</button>
                    <button class="btn btn-info pull-right">Accept request</button>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-xs-12 colsm-12 login-requests-list-item-details">
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                    <span class="login-requests-list-item-field-title">Employee Name :</span>
                    <span>Mr. Arfdsfds</span>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                    <span class="login-requests-list-item-field-title">Employee ID :</span>
                    <span>EMP1001010</span>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                    <span class="login-requests-list-item-field-title">Email :</span>
                    <span>tst@test.com</span>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                    <span class="login-requests-list-item-field-title">Manager :</span>
                    <span>Mr. Abcd bege</span>
                </div>
            </div>
        </div>
</div>