<?php 
$employee_details = $this->employee_details;
$projects_list = $this->projects_list;
$managers_list = $this->managers_list;
$utilities = new application_models_Utilities ();
$user_details = $utilities->get_user_details();
		if($user_details->user_role =='E'){
			$current_project = $this->current_project;
			$current_manager = $this->current_manager;
			$previous_project = $this->previous_project;
			$previous_manager = $this->previous_manager;
		}
?>
<section>
	<div class="container profile-display">
		<div class="profile-header">
			<img src="<?php echo ($employee_details->image_path)? $employee_details->image_path : '/externals/images/default_profile.png'?>" alt="profile image" width="200" height="200">
			<div class="edit-profile-name"><?php echo $employee_details->name;?></div>
		</div>
		<div class="user-profile-information">
			<div class="row">
				<span class="edit-profile-field-title col-lg-3 bold">Employee ID 	<span class='pull-right'>:</span></span>
				<span class="edit-profile-field-value"><?php echo $employee_details->emp_ref;?></span>
			</div>
			<div class="row">
				<span class="edit-profile-field-title col-lg-3">Email address <span class='pull-right'>:</span></span>
				<span class="edit-profile-field-value"><?php echo $employee_details->email;?></span>
			</div>
			<div class="row">
				<span class="edit-profile-field-title col-lg-3" >Address <span class='pull-right'>:</span></span>
				<span class="edit-profile-field-value"><?php echo $employee_details->address;?></span>
			</div>
			<?php if(isset($current_project)){?>
			<div class="row">
				<span class="edit-profile-field-title col-lg-3" >Current project <span class='pull-right'>:</span></span>
				<span class="edit-profile-field-value"><?php echo $current_project['name'];?></span>
			</div>
	<?php } 
		if(isset($current_manager)){
	?>		
			<div class="row">
				<span class="edit-profile-field-title col-lg-3" >Current manager <span class='pull-right'>:</span></span>
				<span class="edit-profile-field-value"><?php echo $current_manager['name'];?></span>
			</div>
			<?php } ?>

			<?php if(isset($previous_project) && $previous_project){?>
			<div class="row">
				<span class="edit-profile-field-title col-lg-3" >Previous project <span class='pull-right'>:</span></span>
				<span class="edit-profile-field-value"><?php echo $previous_project['name'];?></span>
			</div>
	<?php } 
		if(isset($previous_manager) && $previous_project){
	?>		
			<div class="row">
				<span class="edit-profile-field-title col-lg-3" >Previous manager <span class='pull-right'>:</span></span>
				<span class="edit-profile-field-value"><?php echo $previous_manager['name'];?></span>
			</div>
			<?php } ?>
		</div>
		<div class="user-profile-manage-btn-group">
			<button class="btn btn-primary" data-toggle="modal" data-target="#edit-profile">Update profile</button>
		</div>
	</div>
</section>

<div id="edit-profile" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Update your profile</h4>
                </div>
                <div class="modal-body">
                	<div class="row">
                		<?php echo $this->partial('index/includes/employee_form.phtml', array('employee_details' => $employee_details));?>
                	</div>
                </div>
                <div class=""></div>
            </div>
            <!-- /.modal-content -->								
        </div>
        <!-- /.modal-dialog -->
    </div>