<?php 
$employee_details = $this->employee_details;
$projects_list = $this->projects_list;
$managers_list = $this->managers_list;
?>
<section>
	<div class="container profile-display">
		<div class="profile-header">
			<img src="<?php echo ($employee_details->image_path)? $employee_details->image_path : '/externals/images/default_profile.png'?>" alt="profile image" width="200" height="200">
			<div class="edit-profile-name"><?php echo $employee_details->name;?></div>
		</div>
		<div class="user-profile-information">
			<div class="row">
				<span class="edit-profile-field-title">Employee reference :</span>
				<span class="edit-profile-field-value"><?php echo $employee_details->emp_ref;?></span>
			</div>
			<div class="row">
				<span class="edit-profile-field-title">Email address :</span>
				<span class="edit-profile-field-value"><?php echo $employee_details->email;?></span>
			</div>
			<div class="row">
				<span class="edit-profile-field-title">Address :</span>
				<span class="edit-profile-field-value"><?php echo $employee_details->address;?></span>
			</div>
		</div>
		<div class="user-profile-manage-btn-group">
			<button class="btn btn-primary" data-toggle="modal" data-target="#edit-profile">Update profile</button>
		</div>
	</div>
</section>

<div id="edit-profile" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Update your profile</h4>
                </div>
                <div class="modal-body">
                	<div class="row">
                		<?php echo $this->partial('index/includes/employee_form.phtml', array('employee_details' => $employee_details));?>
                	</div>
                </div>
                <div class=""></div>
            </div>
            <!-- /.modal-content -->								
        </div>
        <!-- /.modal-dialog -->
    </div>