<section>
  <div class="container">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3 login-signup-container">
      <div class="">

        <!-- Nav tabs -->

        <div class="btn-group btn-group-justified login-signup-nav-btn-group" role="group">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default"  data-target="#login" aria-controls="login" role="tab" data-toggle="tab">Login</button>
          </div>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default" data-target="#register" aria-controls="register" role="tab" data-toggle="tab">Register</button>
          </div>
        </div>


        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="login">
            <div class="row col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2 login-form-container">
                <form id="login-form" action="" method="post" role="form">
                  <div class="form-group">
                    <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Employee reference" value="">
                  </div>
                  <div class="form-group">
                    <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
                  </div>

                  <div class="form-group">
                      <div class="">
                        <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-primary login-submit" value="Log In">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="">
                        <div class="text-center">
                          <a href="" tabindex="5" class="forgot-password">Forgot Password?</a>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="register">
            <div class="row col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2 register-form-container">
                <form class="form-horizontal" action="<?php echo $this->url(array('action'=>'index','controller'=>'index'),null,true)?>"  role="form">
                  <div class="form-group">
                    <div class="">
                      <input type="text" id="firstName" placeholder="Name" class="form-control" autofocus>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="">
                      <input type="email" id="email" placeholder="Email" class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="">
                      <input type="password" id="password" placeholder="Password" class="form-control">
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="">
                      <select id="country" class="form-control">  
                        <option>Admin</option>
                        <option>Manager</option>
                        <option>Employee</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="">
                      <input type="password" id="password" placeholder="Address" class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="Upload image" class="control-label">Upload image</label>
                    <div class="">
                      <label class="btn btn-default btn-file">
                        Browse <input type="file" style="display: none;">
                      </label>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="Upload resume" class="control-label">Upload resume</label>
                    <div class="">
                      <label class="btn btn-default btn-file">
                        Browse 
                        <input type="file" style="display: none;">
                      </label>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="">
                      <select id="country" class="form-control">
                        <option>Smith</option>
                        <option>Adam</option>
                        <option>Vivek</option>
                      </select>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="">
                      <button type="submit" class="btn btn-primary btn-block">Register</button>
                    </div>
                  </div>
                </form>
                <!-- /form -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>