
<div class='col-md-12 no-padding'>
            <form class="form-horizontal" role="form">
                <h2>Registration Form</h2>
                <div class="form-group">
                
                    <label for="empreference" class="col-sm-3 control-label">Emp reference</label>
                    <div class="col-sm-9">
                        <input type="text" id="firstName" placeholder="Name" class="form-control" autofocus>
                       
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-sm-3 control-label">Email</label>
                    <div class="col-sm-9">
                        <input type="email" id="email" placeholder="Email" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-3 control-label">Password</label>
                    <div class="col-sm-9">
                        <input type="password" id="password" placeholder="Password" class="form-control">
                    </div>
                </div>
              
                <div class="form-group">
                    <label for="role" class="col-sm-3 control-label">role</label>
                    <div class="col-sm-9">
                        <select id="country" class="form-control">
                            <option>Admin</option>
                            <option>Manager</option>
                            <option>Employee</option>
                            
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="Address" class="col-sm-3 control-label">Address</label>
                    <div class="col-sm-9">
                        <input type="password" id="password" placeholder="Address" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                <label for="Upload image" class="col-sm-3 control-label">Upload image</label>
                    <div class="col-sm-9">
                      <label class="btn btn-default btn-file">
    Browse <input type="file" style="display: none;">
</label>
                    </div>
                
                </div>
                  <div class="form-group">
                <label for="Upload resume" class="col-sm-3 control-label">Upload resume</label>
                    <div class="col-sm-9">
                      <label class="btn btn-default btn-file">
    Browse <input type="file" style="display: none;">
</label>
                    </div>
                
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label for="Manager" class="col-sm-3 control-label">Manager</label>
                    <div class="col-sm-9">
                        <select id="country" class="form-control">
                            <option>Smith</option>
                            <option>Adam</option>
                            <option>Vivek</option>
                            
                        </select>
                    </div>
                </div>
               


                <div class="form-group">
                    <div class="col-sm-9 col-sm-offset-3">
                        <button type="submit" class="btn btn-primary btn-block">Register</button>
                    </div>
                </div>
            </form> <!-- /form -->
        
</div>
