 <?php
$active_posts_data = $this->posts_data;
$projects_list = $this->projects_list;
$projects_list = $this->projects_list;
$requested_posts_count = $this->requested_posts_count;
$this->headScript()->appendFile($this->baseUrl('externals\js\admin.js'));

 ?>
 
 
 
 <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
 <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <?php 
                        $utilities = new application_models_Utilities();
                        $user_details = $utilities->get_user_details();
                        if($user_details->user_role == 'A'){
                ?>
                <button onclick="window.location='/admin/jobpostrequests'" class="btn">Job post requests<span class="badge"><?php echo $requested_posts_count['requested_posts_count'];?></span></button>
                     <?php
                        }else if($user_details->user_role == 'M'){
                            ?>
                             <button onclick="window.location='/admin/jobpostrequests'" class="btn">Requested posts<span class="badge"><?php echo $requested_posts_count['requested_posts_count'];?></span></button>
                            <?php
                        }
                ?>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button  id='add-job-trigger'  data-toggle="modal" class="btn pull-right">Add a new Job post</button>
                </div>
            </div>
 </div>
 <div class='col-lg-12 jobs-list-container'>
<?php echo $this->partial('posts/includes/postsdisplay.phtml', array(
    'active_posts_data' => $this->posts_data)); ?>
</div>
     <div id="add-new-job" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Add/Update a Job Post</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
                            <form class="form-horizontal" id='add_posts' method = 'POST'>
                            	<input type="text" hidden="true" name="job_id">
                                <div class="form-group">
                                	<label for="project_name">Project Name</label>
                                    <select required class="form-control" name="project_name" id="project_name">
                                    <option value=''>SELECT</option>
                                    <?php
                                    if($projects_list){
                                        foreach($projects_list as $project_data){
                                           echo "<option value='".$project_data['project_id']."' >".$project_data['name']."</option>"; 
                                                                                       
                                        }
                                    }
                             	           
                                	    ?>
                                            
                                    </select>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                    	<label for="job_title">Job Title</label>
                                        <input required type="text" class="form-control" name="job_title" id="job_title" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                    	<label for="no_of_vacancies">Number of vacancies</label>
                                        <input type="number" class="form-control" name="no_of_vacancies" id="no_of_vacancies" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                    	<label for="salary">Salary</label>
                                        <input type="text" class="form-control" name="salary" id="salary" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                    	<label for="job_description">Job Description</label>
                                        <textarea required name="job_description" id="job_description" class="form-control" rows="3"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                	<div class="">
                                		<label for="key_skills">Required Key skills</label>
                                		<select required name="key_skills" id="key_skills" data-placeholder=" " class="form-control" multiple tabindex="-1">
								        <option value="Empty">&nbsp;</option>
								        <optgroup label="NFC EAST">
								          <option>Dallas Cowboys</option>
								          <option>New York Giants</option>
								          <option>Philadelphia Eagles</option>
								          <option>Washington Redskins</option>
								        </optgroup>
								      </select>
                                	</div>
                                </div>			
                                <div class="form-group">							
                                	<label for="expiry_date">End date for Applicants</label>
                                    <div class="input-group date post-job-date-control" >
	                                    <input required name="expiry_date" type="text" id="expiry_date_datepicker" class="form-control">
	                                    <span class="input-group-addon">
	                                        <span class="glyphicon glyphicon-calendar"></span>
	                                    </span>
	                                </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id ='save_post'>Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->								
        </div>
        <!-- /.modal-dialog -->
    </div>