 <?php
$active_posts_data = $this->posts_data;
$projects_list = $this->projects_list;
$requested_posts_count = $this->requested_posts_count;
$this->headScript()->appendFile($this->baseUrl('externals\js\admin.js'));
$this->headScript()->appendFile($this->baseUrl('externals\js\employee.js'));
$utilities = new application_models_Utilities();
$user_details = $utilities->get_user_details();
$user_role = $user_details->user_role;
if($user_role == 'E'){
    $display_count = isset($this->applied_posts_count)? $this->applied_posts_count :0;
}else { //if($user_role == 'A'){
    $display_count = isset($this->requested_posts_count)? $this->requested_posts_count :0; 
}/*else if($user_role == 'M'){
    $display_count = isset($this->requested_posts_count)? $this->requested_posts_count :0; 
}*/



 ?>
 
 
 
 <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
 <div class="row">
 <?php
             if($user_role == 'M' || $user_role == 'A'){
?>
             <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button onclick="window.location='/admin/jobpostrequests'" class="btn"><?php echo $user_role != 'M'? 'Job post requests' : 'Requested Job Posts'?><span class="badge"><?php echo $display_count;?></span></button>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button  id='add-job-trigger'  data-toggle="modal" class="btn pull-right"><?php echo $user_role != 'M'? 'Add a new Job post' : 'Request a new Job post'?></button>
                </div>
<?php
 }else{
	 if(!$this->display_applied_posts){
?>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button onclick="window.location='/posts/displayappliedjobposts'" class="btn">View Applied Job posts <span class="badge"><?php echo $display_count;?></span></button>
                </div>

<?php
	 }else{
		 ?>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button onclick="window.location='/'" class="btn">Browse all posts </span></button>
                </div>

<?php		 
	 }
 }
 ?>

               
            </div>
 </div>
 <div class='col-lg-12 jobs-list-container'>
<?php echo $this->partial('posts/includes/postsdisplay.phtml', array(
    'active_posts_data' => $this->posts_data)); ?>
</div>
<?php if($user_role != 'E'){
	echo $this->partial('posts/includes/addnewpost.phtml', array(
	'projects_list' => $projects_list, 'current_page' => 'ALL_AVAILABLE_POSTS'));
}
?>

