 <?php
$active_posts_data = $this->posts_data;

 ?>
 
 
 <div class="row">
                <div class="jobs-list">
<?php
if($active_posts_data){
foreach($active_posts_data as $post_data){
?>

<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="panel panel-default">
                            <!-- Default panel contents -->
                            <div class="panel-heading">
                                <div><?php echo $post_data['project_name'];?></div>
                            </div>
                             <div class="panel-body">
                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                                    <p class="lead"><?php echo $post_data['job_description'];?></p>
                                    <p><?php echo $post_data['job_skill_set'];?></p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 pull-right job-list-item-btn-container">
                                    <button class="btn btn-info">
                                        Update details
                                    </button>
                                    <button class="btn btn-danger">
                                        Delete Job
                                    </button>
                                </div>
                                   </div>
                                   </div>
                                   </div>
                        
        
                  
<?php
 }
}

?>
  </div>
                </div>
               