<?php
$employees_list = $this->employees_list;
$this->headLink()->appendStylesheet($this->baseUrl('externals\css\loginrequests.css'));
?>
<div class="container">
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
        <?php
        if($employees_list){
        foreach($employees_list as $employees_data){

        ?>

        <div class="row login-requests-list-item" style='margin-bottom: 20px;'>
            <div class="col-lg-12 col-md-12 col-xs-12 colsm-12 login-requests-list-item-header" >
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6">
                    <span class="lead"><?php echo $employees_data['user_role']=='M'?"Manager":"Employee";?></span>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-xs-12 colsm-12 login-requests-list-item-details">
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                    <span class="login-requests-list-item-field-title">Employee Name :</span>
                    <span><?php echo $employees_data['employee_name'];?></span>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                    <span class="login-requests-list-item-field-title">Employee Reference :</span>
                    <span><?php echo $employees_data['employee_ref'];?></span>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                    <span class="login-requests-list-item-field-title">Email :</span>
                    <span><?php echo $employees_data['email'];?></span>
                </div>
                <?php if ( $employees_data['manager_name']) { ?>
                    <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                        <span class="login-requests-list-item-field-title">Manager :</span>
                        <span><?php echo $employees_data['manager_name'];?></span>
                    </div>
                <?php } else {?>
                    <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
                        <span class="login-requests-list-item-field-title">Address :</span>
                        <span><?php echo $employees_data['address'];?></span>
                    </div>
                <?php }?>

            </div>
        </div>
<?php
}
echo '</div>';
echo '</div>';
}else{
    echo "<h4><p class='text-center text-info col-lg-12'>No employees to display!</p></h4>";
}
?>