
<html lang="en">
<head>
	<meta charset="utf-8">
    

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
	<?php 

	echo	$this->headScript()->prependFile($this->baseUrl('externals\js\jquery-3.1.0.min.js'))->appendFile($this->baseUrl('externals\js\bootstrap.min.js'));

echo $this->headLink()->prependStylesheet($this->baseUrl('externals\css\bootstrap.min.css'))->appendStylesheet($this->baseUrl('externals\css\login.css'));
	?>
	
</head>
<body>
<div class="container-fluid">
<div class='col-md-12 no-padding'>
<html><?php echo $this->layout()->content ?>

</div>
</div>

</body>
</html>