<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
	<?php 
		echo $this->headScript()->prependFile($this->baseUrl('externals\js\jquery-3.1.0.min.js'))->appendFile($this->baseUrl('externals\js\bootstrap.min.js'));

		echo $this->headLink()->prependStylesheet($this->baseUrl('externals\css\bootstrap.min.css'))->appendStylesheet($this->baseUrl('externals\css\styles.css'));
	?>
	
</head>
<body>
    <nav role="navigation" class="navbar navbar-inverse">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <a href="#" class="navbar-brand">Brand</a>
            </div>
            <!-- Collection of nav links, forms, and other content for toggling -->
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="#">Jobs</a></li>
                    <li><a href="#">Login Requests</a></li>
                    <li><a href="#">Projects</a></li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <span class="glyphicon glyphicon-user user-icon"> </span> User name<b class="caret"></b></a>
                        <div role="menu" class="dropdown-menu">
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
<div class="container-fluid">
<div class='col-md-12 no-padding'>

<?php echo $this->layout()->content ?>

</div>
</div>

</body>
</html>