<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Job Portal</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet"> 
	<?php 
		echo $this->headScript()->prependFile($this->baseUrl('externals\js\bootstrap.min.js'))
                                ->prependFile($this->baseUrl('externals\js\jquery-3.1.0.min.js'))
                                ->appendFile($this->baseUrl('externals\js\moment.min.js'))
                                ->appendFile($this->baseUrl('externals\js\chosen.jquery.js'))
                                ->appendFile($this->baseUrl('externals\js\bootstrap-datetimepicker.min.js'))
                                ->appendFile($this->baseUrl('externals\js\dashboard.js'));

		echo $this->headLink()->prependStylesheet($this->baseUrl('externals\css\chosen.css'))
								->prependStylesheet($this->baseUrl('externals\css\bootstrap.min.css'))
                                ->appendStylesheet($this->baseUrl('externals\css\bootstrap-datetimepicker.css'))
                                ->appendStylesheet($this->baseUrl('externals\css\chosen-bootstrap.css'))
                                ->appendStylesheet($this->baseUrl('externals\css\styles.css'));
	?>
	
</head>
<?php
$storage = Zend_Auth::getInstance()->getIdentity();
if($storage->name){
$logged_in_user_name = $storage->name;
}
if ($storage->active_page) {
    $active_page = $storage->active_page;
}
?>
<body>
    <nav role="navigation" class="navbar navbar-inverse">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <a href="/" class="navbar-brand">Company Name</a>
            </div>
            <!-- Collection of nav links, forms, and other content for toggling -->
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                <?php
                        $utilities = new application_models_Utilities();
                        $user_details = $utilities->get_user_details();
                        if($user_details->user_role == 'A'){
                                $jobs_href =  $this->url(array('action'=>'index','controller'=>'admin'),null,true);
                                $login_href = $this->url(array('action'=>'loginrequests','controller'=>'admin'),null,true);
                        }else if ($user_details->user_role == 'E`'){
                             $jobs_href =  $this->url(array('action'=>'index','controller'=>'employee'),null,true);
                        }else if($user_details->user_role == 'M'){
                             $jobs_href =  $this->url(array('action'=>'index','controller'=>'manager'),null,true);
                              $login_href = $this->url(array('action'=>'loginrequests','controller'=>'manager'),null,true);
                        }
                        
                ?>
                    <li class="<?php echo ($active_page == 'posts')?'active':''?>"><a href="<?php echo $jobs_href;?>">Jobs</a></li>
                    <?php
                    if($user_details->user_role !='E'){
                        ?>
                      <li class="<?php echo ($active_page == 'login_requests')?'active':''?>"><a href="<?php echo $login_href;?>">Login Requests</a></li>
                    <?php  
                    }
                    ?>
                    <!--<li><a href="#">Projects</a></li> -->
                    <li class="<?php echo ($active_page == 'profile')?'dropdown active':'dropdown'?>">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <span class="glyphicon glyphicon-user user-icon"> </span> <?php echo $logged_in_user_name;?><b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                        <li><a class="dropdown-item" href="<?php echo $this->url(array('action'=>'editprofile','controller'=>'index'),null,true)?>">Edit profile</a></li>
                        <li><a class="dropdown-item" href="<?php echo $this->url(array('action'=>'logout','controller'=>'index'),null,true)?>">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
<div class="container-fluid">
<div class='col-md-12 no-padding'>

<?php echo $this->layout()->content ?>

</div>
</div>

</body>
</html>