<?php 
$employee_details = $this->employee_details;
$projects_list = $this->projects_list; 
?>
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 register-form-container">
	<form class="form-horizontal" method="POST"
		enctype="multipart/form-data"
		action="<?php echo ($employee_details->eid)? $this->url(array('action'=>'editprofile','controller'=>'index'),null,true) : $this->url(array('action'=>'index','controller'=>'index'),null,true);?>"
		role="form">
		<input type="text" name="eid" value="<?php echo $employee_details->eid?>" hidden="true">
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="full_name">Full name</label> <input type="text"
							name="full_name" id="full_name" placeholder="" value="<?php echo $employee_details->name?>" class="form-control"
							autofocus>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="emp_ref">Employee Reference</label> 
						<input type="text" value="<?php echo $employee_details->emp_ref?>"
							name="emp_ref" id="emp_ref" placeholder="" class="form-control"
							autofocus>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
                    <div class="">
                      <label for="project_id">Project</label>
                      <select id="project_id" name="project_id" class="form-control">
                                    <option value=''>SELECT</option>
                                    <?php
                                    if($projects_list){
                                        foreach($projects_list as $project_data){
                                           echo "<option value='".$project_data['project_id']."' >".$project_data['name']."</option>"; 
                                                                                       
                                        }
                                    }
                             	           
                                	    ?>
                      </select>
                    </div>
                  </div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
                    <div class="">
                      <label for="Manager">Manager</label>
                      <select id="manager_id" name="Manager" class="form-control">  
                      <option value="">Select</option>
                        <option value="1">Admin</option>
                        <option value="2">Manager</option>
                        <option value="3">Employee</option>
                      </select>
                    </div>
                  </div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="email">Email address</label> 
						<input type="email" value="<?php echo $employee_details->email?>"
							id="email" name="email" placeholder="" class="form-control">
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="address">Address</label> 
						<input type="text" id="address" value="<?php echo $employee_details->address?>"
							name="address" placeholder="" class="form-control">
					</div>
				</div>
			</div>
		</div>
		
		<?php if(!$employee_details->eid) {?>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="password">Password</label> 
						<input type="password"
							id="password" name="password" placeholder="" class="form-control">
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="confirm_password">Confirm Password</label> <input
							type="password" id="confirm_password" name="confirm_password"
							placeholder="" class="form-control">
					</div>
				</div>
			</div>
		</div>
		
		<?php } else { ?>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="old_password">Old Password</label> 
						<input type="password"
							id="password" name="old_password" placeholder="" class="form-control">
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="new_password">New Password</label> <input
							type="password" id="new_password" name="new_password"
							placeholder="" class="form-control">
					</div>
				</div>
			</div>
		</div>
		<?php }?>
		<?php if(!$employee_details->eid) {?>
		<div class="form-group">
			<div class="">
				<label for="user_role">Your role</label> 
				<select id="user_role"
					name="user_role" class="form-control">
					<option value="A">Admin</option>
					<option value="M">Manager</option>
					<option value="E">Employee</option>
				</select>
			</div>
		</div>
		<?php }?>
		<div class="form-group">
			<div class="">
				<label for="Upload image" class="control-label">Upload image</label>
				<label class="btn btn-default btn-file"> Browse 
				<input type="file"
					name="user_image" style="display: none;">
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="">
				<label for="Upload resume" class="control-label">Upload resume</label>
				<label class="btn btn-default btn-file"> Browse 
				<input type="file"
					name="user_resume" style="display: none;">
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="">
				<button type="submit" name="<?php echo ($employee_details->eid)?'update':'register'?>" value="<?php echo ($employee_details->eid)?'update':'register'?>"
					class="btn btn-primary btn-block"><?php echo ($employee_details->eid)?'Update profile':'Register'?></button>
			</div>
		</div>
	</form>
	<!-- /form -->
</div>
