<?php 
$employee_details = $this->employee_details;
$projects_list = $this->projects_list; 
$managers_list = $this->managers_list;
?>
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 register-form-container">
	<form id="employee_registration_form" class="form-horizontal" method="POST"
		enctype="multipart/form-data"
		action="<?php echo ($employee_details->eid)? $this->url(array('action'=>'editprofile','controller'=>'index'),null,true) : $this->url(array('action'=>'index','controller'=>'index'),null,true);?>"
		role="form">
		<input type="text" name="eid" value="<?php echo $employee_details->eid?>" hidden="true">
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="full_name">Full name</label> 
						<input type="text" required
							name="full_name" id="full_name" pattern="[a-z|A-Z|.]{6,26}" title="Enter only characters min 6 and maximum 15" placeholder="" value="<?php echo $employee_details->name?>" class="form-control"
							autofocus>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="emp_ref">Employee ID</label> 
						<input type="text" required value="<?php echo $employee_details->emp_ref?>"
							name="emp_ref" id="emp_ref" placeholder="" class="form-control"
							autofocus>
					</div>
				</div>
			</div>
		</div>
		<?php if(!$employee_details->eid) {?>
		<div class="form-group">
			<div class="">
				<label for="user_role">Your role</label> 
				<select id="user_role"
					name="user_role" class="form-control">
					<option value ="">Select</option>
					<option value="M">Manager</option>
					<option value="E">Employee</option>
				</select>
			</div>
		</div>
		<?php }?>

		<?php if(!$employee_details->eid) {?>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
                    <div class="">
                      <label for="project_id">Project</label>
                      <select required id="project_id" name="project_id" class="form-control">
                                    <option value=''>Select</option>
                                    <?php
                                    if($projects_list){
                                        foreach($projects_list as $project_data){
                                           echo "<option value='".$project_data['project_id']."' >".$project_data['name']."</option>"; 
                                                                                       
                                        }
                                    }
                             	           
                                	    ?>
                      </select>
                    </div>
                  </div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
                    <div class="">
                      <label for="Manager">Manager</label>
                      <select required id="manager_id" name="manager_id" class="form-control">  
                      <option value=''>Select</option>
                                    <?php
                                    if($projects_list){
                                        foreach($managers_list as $manager_data){
                                           echo "<option value='".$manager_data['eid']."' >".$manager_data['name']."</option>"; 
                                                                                    
                                        }
                                    }
                             	    ?>
                      </select>
                    </div>
                  </div>
			</div>
		</div>
		<?php }?>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="email">Email address</label> 
						<input required type="email" value="<?php echo $employee_details->email?>"
							id="email" name="email" placeholder="" class="form-control">
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="address">Address</label> 
						<input required type="text" id="address" value="<?php echo $employee_details->address?>"
							name="address" placeholder="" class="form-control">
					</div>
				</div>
			</div>
		</div>
		<div class="form-group">
                                <div class="">
                                    <label for="key_skills">Required Key skills</label>
                                    <select required name="key_skills[]" id="key_skills" data-placeholder=" " class="form-control" multiple tabindex="-1">
                                        <option value="Empty">&nbsp;</option>
                                        <option>Objective C</option>
                                        <option>JSP</option>
                                        <option>JavaScript</option>
                                        <option>XML</option>
                                        <option>Struts</option>
                                        <option>Hibernate</option>
                                        <option>AJAX</option>
                                        <option>PHP4/5</option>
                                        <option>JavaSE</option>
                                        <option>Servlets</option>
                                        <option>Oracle</option>
                                        <option>Spring</option>
                                        <option>jQuery</option>
                                        <option>Bootstrap</option>
                                        <option>MVC</option>
                                        <option>C#</option>
                                        <option>Ruby</option>
                                        <option>Rails</option>
                                        <option>Groovy</option>
                                        <option>Hive</option>
                                        <option>Spark</option>
                                        <option>Hadoop</option>
                                        <option>Pig</option>
                                        <option>R</option>
                                        <option>weblogic</option>
                                        <option>Apache</option>
                                        <option>Tomcat</option>
                                        <option>Derby</option>
                                        <option>MySQL</option>
                                        <option>SQLite</option>
                                        <option>Mangodb</option>
                                        <option>Erlang</option>
                                        <option>Linux</option>
                                        <option>Windows</option>
                                        <option>Mac</option>
                                        <option>Android</option>
                                    </select>
                                </div>
                            </div>
		<?php if(!$employee_details->eid) {?>
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="password">Password</label> 
						<input required type="password"
							id="password" name="password" placeholder="" class="form-control">
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				<div class="form-group">
					<div class="">
						<label for="confirm_password">Confirm Password</label> 
						<input required 
							type="password" id="confirm_password" name="confirm_password"
							placeholder="" class="form-control">
					</div>
				</div>
			</div>
		</div>
		
		<?php } else { ?>
		<div class="row">
<!-- 			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"> -->
<!-- 				<div class="form-group"> -->
<!-- 					<div class=""> -->
<!-- 						<label for="old_password">Old Password</label>  -->
<!-- 						<input required type="password" -->
<!-- 							id="password" name="old_password" placeholder="" class="form-control"> -->
<!-- 					</div> -->
<!-- 				</div> -->
<!-- 			</div> -->
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="form-group">
					<div class="">
						<label for="new_password">New Password</label>
						<input type="password" id="new_password" name="new_password"
							placeholder="" class="form-control">
					</div>
				</div>
			</div>
		</div>
		<?php }?>
		<div class="form-group">
			<div class="">
				<label style="width: 100%"> Upload Profile image 
				<input class="btn btn-default btn-file" type="file"
					name="user_image">
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="">
				<label style="width: 100%"> Upload resume 
				<input class="btn btn-default btn-file" type="file"
					name="user_resume">
				</label>
			</div>
		</div>

		<div class="form-group">
			<div class="">
				<button type="submit" name="<?php echo ($employee_details->eid)?'update':'register'?>" value="<?php echo ($employee_details->eid)?'update':'register'?>"
					class="btn btn-primary btn-block"><?php echo ($employee_details->eid)?'Update profile':'Register'?></button>
			</div>
		</div>
	</form>
	<!-- /form -->
</div>
<script>

	var emp_skill_set = '<?php echo $employee_details->key_skills; ?>';
	if (emp_skill_set) {
		var skills = emp_skill_set.split(',');
		$('#key_skills').val(skills).trigger('chosen:updated');
	} else {
		$('#key_skills').val([]).trigger('chosen:updated');
	}

</script>