<?php
$active_posts_data = $this->posts_data;
$projects_list = $this->projects_list;
$this->headScript()->appendFile($this->baseUrl('externals\js\admin.js'));
$this->headScript()->appendFile($this->baseUrl('externals\js\manager.js'));
$this->headScript()->appendFile($this->baseUrl('externals\js\employee.js'));
$this->headLink()->appendStylesheet($this->baseUrl('externals\css\loginrequests.css'));
$utilities = new application_models_Utilities();
$user_details = $utilities->get_user_details();
$user_role = $user_details->user_role;

?>
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
    <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <button onclick="window.location='/'" class="btn">Browse all posts</button>
            </div>
    </div>
</div>


<div class="col-lg-12">
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1" style="margin-top: 27px;">
    <div class="row">
             <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
             <select required id="project_id"
					name="project_id" class="form-control">
                    <option value="">Select project</option>
					<?php
                    if($this->projects_list){
                        foreach($this->projects_list as $project_data){
                            echo  '<option value="'.$project_data['project_id'].'">'.$project_data['name'].'</option>';
                        }
                    }
                    ?>
				</select>
               
        
            </div>
             <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <select required id="project_id"
					name="project_id" class="form-control">
                    <option value="">Select Job</option>
					<?php
                    if($this->posts_data){
                        foreach($this->posts_data as $post_data){
                            echo  '<option value="'.$post_data['post_id'].'">'.$post_data['job_title'].'</option>';
                        }
                    }
                    ?>
				</select>
               
        
            </div>
    </div>
</div>
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 no-padding login-requests-container" id ='applied-job-posts-container'>
 <?php echo $this->partial('manager/includes/applied_posts_display.phtml', array('applied_job_posts_data' => $this->applied_job_posts_data, )); ?>
</div>
</div>