<?php
$active_posts_data = $this->posts_data;
$projects_list = $this->projects_list;
$this->headScript()->appendFile($this->baseUrl('externals\js\admin.js'));
$this->headScript()->appendFile($this->baseUrl('externals\js\employee.js'));
$this->headLink()->appendStylesheet($this->baseUrl('externals\css\loginrequests.css'));
$utilities = new application_models_Utilities();
$user_details = $utilities->get_user_details();
$user_role = $user_details->user_role;

?>
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
    <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <button onclick="window.location='/'" class="btn">Browse all posts</button>
            </div>
    </div>
</div>


<div class="col-lg-12">
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1" style="margin-top: 27px;">
    <div class="row">
             <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
             <select required id="project_id"
					name="project_id" class="form-control">
                    <option value="">Select project</option>
					<?php
                    if($this->projects_list){
                        foreach($this->projects_list as $project_data){
                            echo  '<option value="'.$project_data['project_id'].'">'.$project_data['name'].'</option>';
                        }
                    }
                    ?>
				</select>
               
        
            </div>
             <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <select required id="project_id"
					name="project_id" class="form-control">
                    <option value="">Select Job</option>
					<?php
                    if($this->posts_data){
                        foreach($this->posts_data as $post_data){
                            echo  '<option value="'.$post_data['post_id'].'">'.$post_data['job_title'].'</option>';
                        }
                    }
                    ?>
				</select>
               
        
            </div>
    </div>
</div>
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 no-padding login-requests-container">
<?php
$applied_job_posts_data =  $this->applied_job_posts_data; 
if($applied_job_posts_data){
    foreach($applied_job_posts_data as $applied_job_post_data){

    ?>
<div class="row login-requests-list-item" style='margin-bottom: 20px;'>
    <div class="col-lg-12 col-md-12 col-xs-12 colsm-12 login-requests-list-item-header" >
        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6">
            <span class="lead"><?php echo $applied_job_post_data['name'];?></span>
        </div>
        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-btn-group">
            <button class="btn btn-danger pull-right delete-login-request" data-request-id ="<?php echo $login_request['request_id'];?>" >Delete request</button>
            <button class="btn btn-info pull-right approve-login-request " data-request-id ="<?php echo $login_request['request_id'];?>">Accept request</button>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-xs-12 colsm-12 login-requests-list-item-details">
        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
            <span class="login-requests-list-item-field-title">Key skills :</span>
            <span><?php echo $applied_job_post_data['key_skills'];?></span>
        </div>
        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
            <span class="login-requests-list-item-field-title">Employee Reference :</span>
            <span><?php echo $applied_job_post_data['emp_ref'];?></span>
        </div>
        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
            <span class="login-requests-list-item-field-title">Email :</span>
            <span><?php echo $applied_job_post_data['email'];?></span>
        </div>
        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
            <span class="login-requests-list-item-field-title">Manager :</span>
            <span><?php echo $applied_job_post_data['name'];?></span>
        </div>
    </div>
</div>

<?php
}
}else{
    echo "<h4><p class='text-center text-info col-lg-12'>No login requests to display.</p></h4>";
}

?>
</div>
</div>