<?php
$active_posts_data = $this->posts_data;
$projects_list = $this->projects_list;
$this->headScript()->appendFile($this->baseUrl('externals\js\admin.js'));
$this->headScript()->appendFile($this->baseUrl('externals\js\employee.js'));
$utilities = new application_models_Utilities();
$user_details = $utilities->get_user_details();
$user_role = $user_details->user_role;
?>
<?php echo $this->partial('posts/includes/dashboardheader.phtml', array(
    'requested_posts_count' => $this->requested_posts_count, 'currenct_page' => 'POSTS_INDEX')); ?>


<?php if($user_role != 'E'){
    echo $this->partial('posts/includes/addnewpost.phtml', array(
        'projects_list' => $projects_list, 'current_page' => 'ALL_AVAILABLE_POSTS'));
}
?>
