<?php
$login_requests_data = $this->login_requests_data;

?>

<?php
     $this->headLink()->appendStylesheet($this->baseUrl('externals\css\loginrequests.css'));
     $this->headScript()->prependFile($this->baseUrl('externals\js\loginrequests.js'))
?>

<div class ='col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 no-padding login-requests-container'>
        <?php echo $this->partial('loginrequests/includes/loginrequestsdisplay.phtml', array(
    'login_requests_data' => $this->login_requests_data)); ?>
</div>

