<?php
$projects_list = $this->projects_list;
$current_page = $this->current_page;
?>
<div id="add-new-job" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Add/Update a Job Post</h4>
            </div>
            <form class="form-horizontal" id='add_post' method = 'POST'>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
                            <input type="text" value="<?php echo $current_page;?>" id="add-job-request-source" hidden>
                            <input type="text" hidden="true" name="job_id">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <label for="project_name">Project Name</label>
                                        <select required class="form-control" name="project_name" id="project_name">
                                            <option value=''>SELECT</option>
                                            <?php
                                            if($projects_list){
                                                foreach($projects_list as $project_data){
                                                    echo "<option value='".$project_data['project_id']."' >".$project_data['name']."</option>";

                                                }
                                            }

                                            ?>

                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <div class="form-group">
                                        <div class="">
                                            <label for="job_title">Job Title</label>
                                            <input required type="text" class="form-control" name="job_title" id="job_title" placeholder="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <div class="form-group">
                                        <div class="">
                                            <label for="job_location">Job Location</label>
                                            <select required class="form-control" name="job_location" id="job_location">
                                                <option value=''>SELECT</option>
                                                <option value="San Francisco">San Francisco</option>
                                                <option value="New York City">New York City</option>
                                                <option value="Chicago">Chicago</option>
                                                <option value="Los Angeles">Los Angeles</option>
                                                <option value="Houston">Houston</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <div class="form-group">
                                        <div class="">
                                            <label for="no_of_vacancies">Number of vacancies</label>
                                            <input required type="number"  min = "0" class="form-control" name="no_of_vacancies" id="no_of_vacancies" placeholder="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <div class="form-group">
                                        <div class="">
                                            <label for="salary">Salary</label>
                                            <input required type="text" class="form-control" name="salary" id="salary" placeholder="">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <div class="form-group">
                                        <div class="">
                                            <label for="experience">Experience required(Years)</label>
                                            <input required  type="number" min = "0" class="form-control" name="experience" id="experience" placeholder="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <div class="form-group">
                                        <label for="expiry_date">End date for Applicants</label>
                                        <div class="input-group date post-job-date-control" >
                                            <input required name="last_date_for_applicants" type="text" id="expiry_date_datepicker" class="form-control">
			                                    <span class="input-group-addon">
			                                        <span class="glyphicon glyphicon-calendar"></span>
			                                    </span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="">
                                    <label for="key_skills">Required Key skills</label>
                                    <select name="key_skills" id="key_skills" data-placeholder=" " class="form-control" multiple tabindex="-1">
                                        <option value="Empty">&nbsp;</option>
                                        <option>Objective C</option>
                                        <option>JSP</option>
                                        <option>JavaScript</option>
                                        <option>XML</option>
                                        <option>Struts</option>
                                        <option>Hibernate</option>
                                        <option>AJAX</option>
                                        <option>PHP4/5</option>
                                        <option>JavaSE</option>
                                        <option>Servlets</option>
                                        <option>Oracle</option>
                                        <option>Spring</option>
                                        <option>jQuery</option>
                                        <option>Bootstrap</option>
                                        <option>MVC</option>
                                        <option>C#</option>
                                        <option>Ruby</option>
                                        <option>Rails</option>
                                        <option>Groovy</option>
                                        <option>Hive</option>
                                        <option>Spark</option>
                                        <option>Hadoop</option>
                                        <option>Pig</option>
                                        <option>R</option>
                                        <option>weblogic</option>
                                        <option>Apache</option>
                                        <option>Tomcat</option>
                                        <option>Derby</option>
                                        <option>MySQL</option>
                                        <option>SQLite</option>
                                        <option>Mangodb</option>
                                        <option>Erlang</option>
                                        <option>Linux</option>
                                        <option>Windows</option>
                                        <option>Mac</option>
                                        <option>Android</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="">
                                    <label for="job_description">Job Description</label>
                                    <textarea required name="job_description" id="job_description" class="form-control" rows="3"></textarea>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id ='save_post'>Save changes</button>
            </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->