<?php
$utilities = new application_models_Utilities();
$user_details = $utilities->get_user_details();
$user_role = $user_details->user_role;
$current_page = $this->currenct_page;
if($user_role == 'E'){
    $display_count = isset($this->applied_posts_count)? $this->applied_posts_count :0;
}else { //if($user_role == 'A'){
    $display_count = isset($this->requested_posts_count)? $this->requested_posts_count :0;
}/*else if($user_role == 'M'){
    $display_count = isset($this->requested_posts_count)? $this->requested_posts_count :0;
}*/
?>
<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
    <div class="row">
        <?php
        if($user_role == 'M' || $user_role == 'A'){
            ?>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <button onclick="window.location='<?php echo ($user_role == 'A')? (($current_page == 'POSTS_INDEX')?'/admin/jobpostrequests' : '/admin/') : (($current_page == 'POSTS_INDEX')?'/manager/jobpostrequests' : '/manager/'); ?>'" class="btn"><?php echo ($user_role != 'A')? (($current_page == 'POSTS_INDEX')? 'Requested Job Posts' : 'Browse all Posts') : (($current_page == 'POSTS_INDEX')? 'Job post requests' : 'Browse all Posts'); ?>
                    <?php if($current_page == 'POSTS_INDEX') {
                        echo "<span class=\"badge\">$display_count</span>";
                    }?>
                </button>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <button  id='add-job-trigger'  data-toggle="modal" class="btn pull-right"><?php echo ($user_role == 'A')?'Add a new Job post':'Request for a new Job post'; ?> </button>
                <?php  if($user_role == 'M') { ?>
                    <button onclick="window.location='/manager/chooseemployeesforjob'" id='choose-employees-trigger' class="btn pull-right">Choose employees for job</button>
                <?php }?>
            </div>
            <?php
        }else{
            if(!$this->display_applied_posts){
                ?>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button onclick="window.location='/posts/displayappliedjobposts'" class="btn">View Applied Job posts <span class="badge"><?php echo $display_count;?></span></button>
                </div>

                <?php
            }else{
                ?>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button onclick="window.location='/'" class="btn">Browse all posts </span></button>
                </div>

                <?php
            }
        }
        ?>


    </div>
</div>