<?php
$active_posts_data = $this->active_posts_data;
$utilities = new application_models_Utilities();
$user_details = $utilities->get_user_details();
$user_role = $user_details->user_role;
?>

<div class="row">
	<div class="jobs-list">
<?php
if ($active_posts_data) {
	foreach ( $active_posts_data as $post_data ) {
		?>

<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
			<div class="panel panel-default job-list-item">
				<!-- Default panel contents -->
				<div class="panel-heading">
					<div class="row">
						<div class="<?php echo ($post_data['status'] == 'P')? 'col-lg-7 col-md-7 col-sm-7 col-xs-7': 'col-lg-12 col-md-12 col-sm-12 col-xs-12'; ?>"><?php echo $post_data['project_name'];?></div>
						<?php if ($post_data['status'] == 'P') { ?>
							<div class="col-lg-5 col-md-5 col-sm-5 col-xs-5"><span class="pull-right">Posted by: <?php echo $post_data['name']; ?></span></div>
						<?php }?>
					</div>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
							<p class="lead"><?php echo $post_data['job_description'];?></p>
							<p><?php echo $post_data['job_skill_set'];?></p>
						</div>
						<div
							class="col-lg-3 col-md-3 col-sm-3 col-xs-3 pull-right job-list-item-btn-container">
							<button class="btn btn-info <?php echo ($post_data['status'] == 'P' && $user_role == 'A')?'approve-post':($user_role != 'E' ?'update_posts' :'apply_job_post'); ?>"
								data-post-id='<?php echo $post_data['post_id'];?>'><?php echo ($post_data['status'] == 'P' && $user_role == 'A')? 'Approve post' : ($user_role != 'E' ?'Update details' :'Appply') ?></button>
								<?php
								if($user_role != 'E'){
									?>
<button class="btn btn-danger delete_post"
								data-post-id='<?php echo $post_data['post_id'];?>' data-current-page="<?php echo ($post_data['status'] == 'P')?'jobpostrequests':'index'?>">Delete Job</button>
							<?php
								}
								?>
							
						</div>
					</div>
					<div class="row">
						<div class="row job-info-field-set">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
								<div class="job-info-field">
									<span class="job-info-field-title">Salary range :</span> 
									<span class="job-info-field-value"><?php echo $post_data['salary']; ?></span>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
								<div class="job-info-field">
									<span class="job-info-field-title">Location :</span>
									<span class="job-info-field-value"><?php echo "TBH"; ?></span>
								</div>
							</div>
						</div>
						<div class="row job-info-field-set">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
								<div class="job-info-field">
									<span class="job-info-field-title">Number of Vacancies :</span>
									<span class="job-info-field-value"><?php echo $post_data['no_of_vacancies']; ?></span>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
								<div class="job-info-field">
									<span class="job-info-field-title">Project name :</span> 
									<span class="job-info-field-value"><?php echo $post_data['project_name']; ?></span>
								</div>
							</div>
						</div>
						<div class="row job-info-field-set">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
								<div class="job-info-field">
									<span class="job-info-field-title">Posted date :</span>
									<span class="job-info-field-value"><?php echo $post_data['date_of_modification']; ?></span>
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
								<div class="job-info-field">
									<span class="job-info-field-title">Applicants end date :</span> 
									<span class="job-info-field-value"><?php echo  $post_data['date_of_modification'];?></span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
                  
<?php
	}
} else {
	echo "<h4><p class='text-center text-info col-lg-12'>No posts to display.</p></h4>";
}

?>
  </div>
</div>
