<?php 
$projects_list = $this->projects_list; 
$managers_list = $this->managers_list;
$this->headScript()->appendFile($this->baseUrl('externals\js\browseemployees.js'));
?>
<div class="row login-requests-container">
	<div class="container">
	    <div class="row">
	        <div class="col-lg-4 col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-md-4 col-sm-4 col-xs-4">
	            <div class="form-group">
	                <div class="">
	                    <label for="project_id">Project</label>
	                    <select required id="project_id" name="project_id" class="form-control">
	                        <option value=''>Select</option>
	                        <?php
	                        if($projects_list){
	                            foreach($projects_list as $project_data){
	                                echo "<option value='".$project_data['project_id']."' >".$project_data['name']."</option>";
	
	                            }
	                        }
	
	                        ?>
	                    </select>
	                </div>
	            </div>
	        </div>
	        <div class="col-lg-4 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-md-4 col-sm-4 col-xs-4">
	            <div class="form-group">
	                <div class="">
	                    <label for="Manager">Manager</label>
	                    <select required id="manager_id" name="manager_id" class="form-control">
	                        <option value=''>Select</option>
	                        <?php
	                        if($projects_list){
	                            foreach($managers_list as $manager_data){
	                                echo "<option value='".$manager_data['eid']."' >".$manager_data['name']."</option>";
	
	                            }
	                        }
	                        ?>
	                    </select>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>

<?php 
if($employees_list){
    foreach($employees_list as $employees_data){

    ?>
    
		<div class="row login-requests-list-item" style='margin-bottom: 20px;'>
		    <div class="col-lg-12 col-md-12 col-xs-12 colsm-12 login-requests-list-item-header" >
		        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6">
		            <span class="lead"><?php echo $employees_data['user_role']=='M'?"Manager":"Employee";?></span>
		        </div>
		    </div>
		    <div class="col-lg-12 col-md-12 col-xs-12 colsm-12 login-requests-list-item-details">
		        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
		            <span class="login-requests-list-item-field-title">Employee Name :</span>
		            <span><?php echo $employees_data['name'];?></span>
		        </div>
		        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
		            <span class="login-requests-list-item-field-title">Employee Reference :</span>
		            <span><?php echo $employees_data['emp_ref'];?></span>
		        </div>
		        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
		            <span class="login-requests-list-item-field-title">Email :</span>
		            <span><?php echo $employees_data['email'];?></span>
		        </div>
		        <div class="col-lg-6 col-md-6 col-xs-6 colsm-6 login-requests-list-item-field">
		            <span class="login-requests-list-item-field-title">Address :</span>
		            <span><?php echo $employees_data['address'];?></span>
		        </div>
		    </div>
		</div>
	</div>

<?php
}
}else{
    echo "<h4><p class='text-center text-info col-lg-12'>No employees to display!</p></h4>";
}

?>
