
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button class="btn">Job post requests<span class="badge">4</span></button>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button data-target="#add-new-job" data-toggle="modal" class="btn pull-right">Add a new Job post</button>
                </div>
            </div>
        </div>
    </section>

    <section class="jobs-list-container">
        <div class="container">
            <div class="row">
                <div class="jobs-list">
                	<div class="row">
					  <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
					    <div class="job-container">
					      <div data-toggle="collapse" data-target="#details" class="job-header">
					        <div class="row">
					          <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
					            <p class="lead">Job Header</p>
					            <p>Job description</p>
					          </div>
					          <div class="toggle-icon glyphicon glyphicon-chevron-down pull-right"></div>
					        </div>
					      </div>
					      <div class="collapse" id="details">
					        <div class="job-complete-details">
					          <p class="lead">Job basic reuirements</p>
					          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
					        </div>
					        <div class="job-action-buttons">
					          <div class="row">
					            <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-8 col-xs-offset-4">
					              <button class="btn btn-primary">Update job details</button>
					              <button class="btn btn-danger">Delete job post</button>
					            </div>
					          </div>
					        </div>
					      </div>
					    </div>
					  </div>
					</div>
                </div>
            </div>
        </div>
    </section>

    <div id="add-new-job" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Add/Update a Job Post</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
                            <form class="form-horizontal">
                            	<input type="text" hidden="true" name="job_id">
                                <div class="form-group">
                                	<label for="project_name">Project Name</label>
                                    <select required class="form-control" name="project_name" id ="project_name">
                                            <option>Sample 1</option>
                                            <option>Sample 2</option>
                                            <option>Sample 3</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                    	<label for="job_title">Job Title</label>
                                        <input required type="text" class="form-control" name="job_title" id="job_title" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                    	<label for="no_of_vacancies">Number of vacancies</label>
                                        <input type="number" class="form-control" name="no_of_vacancies" id="no_of_vacancies" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                    	<label for="salary">Salary</label>
                                        <input type="text" class="form-control" name="salary" id="salary" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                    	<label for="job_description">Job Description</label>
                                        <textarea required name="job_description" id="job_description" class="form-control" rows="3"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                	<div class="">
                                		<label for="key_skills">Required Key skills</label>
                                		<select required name="key_skills" id="key_skills" data-placeholder=" " class="form-control" multiple tabindex="6">
								        <option value="Empty">&nbsp;</option>
								        <optgroup label="NFC EAST">
								          <option>Dallas Cojjwboys</option>
								          <option>New York Giants</option>
								          <option>Philadelphia Eagles</option>
								          <option>Washington Redskins</option>
								        </optgroup>
								        <optgroup label="NFC NORTH">
								          <option>Chicago Bears</option>
								          <option>Detroit Lions</option>
								          <option>Green Bay Packers</option>
								          <option>Minnesota Vikings</option>
								        </optgroup>
								        <optgroup label="NFC SOUTH">
								          <option>Atlanta Falcons</option>
								          <option>Carolina Panthers</option>
								          <option>New Orleans Saints</option>
								          <option>Tampa Bay Buccaneers</option>
								        </optgroup>
								        <optgroup label="NFC WEST">
								          <option>Arizona Cardinals</option>
								          <option>St. Louis Rams</option>
								          <option>San Francisco 49ers</option>
								          <option>Seattle Seahawks</option>
								        </optgroup>
								        <optgroup label="AFC EAST">
								          <option>Buffalo Bills</option>
								          <option>Miami Dolphins</option>
								          <option>New England Patriots</option>
								          <option>New York Jets</option>
								        </optgroup>
								        <optgroup label="AFC NORTH">
								          <option>Baltimore Ravens</option>
								          <option>Cincinnati Bengals</option>
								          <option>Cleveland Browns</option>
								          <option>Pittsburgh Steelers</option>
								        </optgroup>
								        <optgroup label="AFC SOUTH">
								          <option>Houston Texans</option>
								          <option>Indianapolis Colts</option>
								          <option>Jacksonville Jaguars</option>
								          <option>Tennessee Titans</option>
								        </optgroup>
								        <optgroup label="AFC WEST">
								          <option>Denver Broncos</option>
								          <option>Kansas City Chiefs</option>
								          <option>Oakland Raiders</option>
								          <option>San Diego Chargers</option>
								        </optgroup>
								      </select>
                                	</div>
                                </div>
                                <div class='form-group'>
                                	<label for="expiry_date">End date for Applicants</label>
                                    <div class='input-group date post-job-date-control' id="expiry_date_datepicker">
	                                    <input required name="expiry_date" type='text' class="form-control" />
	                                    <span class="input-group-addon">
	                                        <span class="glyphicon glyphicon-calendar"></span>
	                                    </span>
	                                </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="panel panel-default">
                            <!-- Default panel contents -->
                            <div class="panel-heading">
                                <div calss ='project_name'><span class="text-primary project_name">Linked in file search -</span>  <span class = 'text-warning project_name'>Android developer</span></div>  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 pull-right job-list-item-btn-container">
                                    <button class="btn btn-info update_posts" data-post-id="19">
                                        Update
                                    </button>
                                    <button class="btn btn-danger delete_post" data-post-id="19">
                                        Delete
                                    </button>
                                </div>
                              
                            </div>
                             <div class="panel-body">
                               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><span class ='project_name'>Job description:</span>
                                    <span class="">for project managementttttttttttttttttttsdfjsdgnjsldkngvlsdfngsfrgsnfkg;nsflkgn fndslkgnsldgj nklgnfdklsgkfsgkfn nvfngvfngsndgjsd;j nkgndsgklsngislnvnfdk nklndsgnfsgi nnnfglfsngn nglfndgfigj nnfkgnfngnfgln nngsfngknfgn nnfdgnfhbkln nlkgsgsjrfgj nnknfghnsfn </span>
                                   
                                </div>
                               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><span>Job skill set:</span><span>Apache,ApacheApacheApacheApacheApache</span><span></span></div>
                               
                                   </div>
                                   </div>
                                   </div>