
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button class="btn">Job post requests<span class="badge">4</span></button>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <button data-target="#add-new-job" data-toggle="modal" class="btn pull-right">Add a new Job post</button>
                </div>
            </div>
        </div>
    </section>

    <section class="jobs-list-container">
        <div class="container">
            <div class="row">
                <div class="jobs-list">
                    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
                        <div class="panel panel-default">
                            <!-- Default panel contents -->
                            <div class="panel-heading">
                                <div>Project title</div>
                            </div>
                            <div class="panel-body">
                                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                                    <p class="lead">Job title</p>
                                    <p>Job description</p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 pull-right job-list-item-btn-container">
                                    <button class="btn btn-info">
                                        Update details
                                    </button>
                                    <button class="btn btn-danger">
                                        Delete Job
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div id="add-new-job" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
                            <form class="form-horizontal">
                                <div class="form-group">
                                    <select class="form-control">
                                            <option>1</option>
                                            <option>2</option>
                                            <option>3</option>
                                            <option>4</option>
                                            <option>5</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                        <input type="text" class="form-control" id="" placeholder="Job Title">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                        <input type="number" class="form-control" id="" placeholder="Number of vacancies">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="">
                                        <textarea class="form-control" rows="3"></textarea>
                                    </div>
                                </div>
                                <div class="form-control">
                                <div class='input-group date' id='datetimepicker1'>
                                        <input type='text' class="form-control" />
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->