<?php
$projects_list = $this->projects_list;
$this->headScript()->appendFile($this->baseUrl('externals\js\admin.js'));
$utilities = new application_models_Utilities();
$user_details = $utilities->get_user_details();
$user_role = $user_details->user_role;
?>



<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <button class="btn" onclick="window.location='/admin'">Browse all Posts<span class="badge"><?php echo $requested_posts_count['requested_posts_count'];?></span></button>
        </div>
        
        <?php
        /*<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <button  id='add-job-trigger'  data-toggle="modal" class="btn pull-right"><?php echo $user_role != 'M'? 'Add a new Job post' : 'Request a new Job post'?></button>
        </div>*/
        ?>
    </div>
</div>

<div class='col-lg-12 jobs-list-container'>
    <?php echo $this->partial('posts/includes/postsdisplay.phtml', array(
        'active_posts_data' => $this->active_posts_data));?>
</div>
<?php if($user_role != 'E'){
    echo $this->partial('posts/includes/addnewpost.phtml', array(
        'projects_list' => $projects_list, 'current_page' => 'JOB_POST_REQUESTS'));
}
?>