<?php
$projects_list = $this->projects_list;
$this->headScript()->appendFile($this->baseUrl('externals\js\admin.js'));

?>



<?php echo $this->partial('posts/includes/dashboardheader.phtml', array(
    'requested_posts_count' => $this->requested_posts_count)); ?>

<div class='col-lg-12 jobs-list-container'>
    <?php echo $this->partial('posts/includes/postsdisplay.phtml', array(
        'active_posts_data' => $this->active_posts_data));?>
</div>
<?php if($user_role != 'E'){
    echo $this->partial('posts/includes/addnewpost.phtml', array(
        'projects_list' => $projects_list, 'current_page' => 'JOB_POST_REQUESTS'));
}
?>